In [1]:
import os
import torch
import pandas as pd
from IPython.display import Image as IPImage, display
from src.feature_extraction.data_utils import *
from src.feature_extraction.utils import login_hf, extract_features
from src.feature_extraction.df_utils import extract_and_save

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

/Users/mac/Desktop/CIL-FM/Continual-FM/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-06-08 12:53:11.534600: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
# os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

# hf_token = """<put your token>"""
    
# login_hf(token=hf_token)

In [4]:
extract_and_save(model_name='PanDerm', data_name='dmf', start=0, end=20, batch_size=10)

loading model checkpoint
normalization method:  imagenet
PanDerm model loaded on cpu

Processing Batches:  50%|█████     | 1/2 [00:05<00:05,  5.82s/it]

Saved batch to outputs/panderm_dmf_pre.csv.
Time to compute embeddings for batch 1:  5.815959930419922 seconds

Processing Batches: 100%|██████████| 2/2 [00:10<00:00,  5.22s/it]

Saved batch to outputs/panderm_dmf_pre.csv.
Time to compute embeddings for batch 2:  4.6249940395355225 seconds

Data saved to outputs/panderm_dmf_.csv

In [5]:
df = pd.read_csv('outputs/panderm_dmf_.csv')
print(df.shape)
df.head()

(20, 1028)

,0,1,2,3,4,5,6,7,8,9,...,1018,1019,1020,1021,1022,1023,image_idx,image_id,class,cell_type_idx
0,0.487167,0.156445,-0.030225,0.145460,-0.102276,0.441302,-0.320723,-0.050795,-0.939699,-0.021571,...,-0.052562,-0.533446,0.296918,-0.317562,-0.091584,-0.371113,1,D204a,bcc,2
1,-0.023529,0.155961,-0.197619,-0.425059,-0.082558,0.277086,-0.527295,0.288618,-0.859852,-0.060173,...,-0.183697,0.032624,-0.192555,-0.108937,-0.209558,-0.810130,2,D226b,nv,1
2,-0.111684,0.156068,-0.230510,-0.517580,-0.289519,0.138093,-0.581007,0.218740,-0.587512,0.047256,...,-0.180578,-0.239246,-0.253699,-0.155557,-0.290111,-0.543180,3,D226c,nv,1
3,-0.251463,0.155860,-0.149105,-0.366408,-0.310290,0.401975,-0.097434,0.176338,-0.698493,-0.395577,...,-0.145016,-0.371768,-0.320429,0.181634,-0.199145,-0.812157,4,D227,nv,1
4,0.079386,0.156490,0.289718,-0.084208,0.040974,0.478035,-0.234446,-0.315274,-0.440029,-0.434566,...,-0.335805,-0.302733,0.218538,0.067234,-0.071715,-0.125109,5,D231,akiec,3

In [6]:
df = pd.read_csv('outputs/panderm_dmf.csv')
df.head()

,0,1,2,3,4,5,6,7,8,9,...,1018,1019,1020,1021,1022,1023,image_idx,image_id,class,cell_type_idx
0,0.487167,0.156445,-0.030225,0.145460,-0.102276,0.441302,-0.320723,-0.050795,-0.939699,-0.021571,...,-0.052562,-0.533446,0.296918,-0.317562,-0.091584,-0.371113,1,D204a,bcc,2
1,-0.023529,0.155961,-0.197619,-0.425059,-0.082558,0.277086,-0.527295,0.288618,-0.859852,-0.060173,...,-0.183697,0.032625,-0.192554,-0.108937,-0.209559,-0.810130,2,D226b,nv,1
2,-0.111684,0.156068,-0.230510,-0.517580,-0.289520,0.138093,-0.581008,0.218741,-0.587512,0.047256,...,-0.180579,-0.239246,-0.253699,-0.155557,-0.290111,-0.543179,3,D226c,nv,1
3,-0.251462,0.155860,-0.149106,-0.366408,-0.310290,0.401975,-0.097433,0.176338,-0.698494,-0.395577,...,-0.145016,-0.371768,-0.320429,0.181634,-0.199145,-0.812157,4,D227,nv,1
4,0.079386,0.156490,0.289719,-0.084207,0.040974,0.478035,-0.234446,-0.315274,-0.440029,-0.434566,...,-0.335805,-0.302733,0.218538,0.067233,-0.071715,-0.125109,5,D231,akiec,3