In [1]:
import os
import torch
import pandas as pd
from IPython.display import Image as IPImage, display
from src.feature_extraction.data_utils import *
from src.feature_extraction.utils import login_hf, extract_features
from src.feature_extraction.df_utils import extract_and_save

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

/Users/mac/Desktop/CIL-FM/Continual-FM/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-06-08 12:20:02.054851: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
# os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

# hf_token = """<put your token>"""
    
# login_hf(token=hf_token)

In [5]:
base_ham_path = 'data/ham'
os.listdir(base_ham_path)

[]

In [6]:
base_d7p_path = 'data/d7p'
os.listdir(base_d7p_path)

['.DS_Store', 'release_v0']

In [7]:
base_dmf_path = 'data/dmf/DMF'
os.listdir(base_dmf_path)

['images', 'meta-dmf.csv']

In [8]:
d7p_pths = get_d7p_paths(base_d7p_path)
dmf_pths = get_dmf_paths(base_dmf_path)
# ham_pths = get_ham_paths(base_ham_path, part=1) # as HAM consests of 2 parts

In [2]:
extract_and_save(model_name='PanDerm', data_name='d7p', start=0, end=20, batch_size=10)

loading model checkpoint

/Users/mac/Desktop/CIL-FM/Continual-FM/venv/lib/python3.10/site-packages/torch/functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:3550.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

normalization method:  imagenet
PanDerm model loaded on cpu

Processing Batches:  50%|█████     | 1/2 [00:04<00:04,  4.11s/it]

Saved batch to outputs/panderm_d7p_pre.csv.
Time to compute embeddings for batch 1:  4.114130973815918 seconds

Processing Batches: 100%|██████████| 2/2 [00:08<00:00,  4.25s/it]

Saved batch to outputs/panderm_d7p_pre.csv.
Time to compute embeddings for batch 2:  4.381310939788818 seconds

Data saved to outputs/panderm_d7p_.csv

In [4]:
df = pd.read_csv('outputs/panderm_d7p_.csv')
print(df.shape)
df.head()

(20, 1026)

,0,1,2,3,4,5,6,7,8,9,...,1016,1017,1018,1019,1020,1021,1022,1023,image_id,class
0,0.093148,0.155922,-0.227682,0.131200,-0.021234,0.206294,-0.418440,0.222322,-0.729207,-0.040594,...,0.151985,0.256870,-0.177419,-0.852223,-0.112196,-0.166880,-0.261960,0.195685,1,basal cell carcinoma
1,0.074431,0.156090,-0.149146,0.053283,0.158131,-0.160206,0.198405,0.098455,-1.345160,0.027786,...,0.844300,0.128064,-0.222104,-0.524728,-0.106959,0.027761,-0.235939,-0.006325,2,basal cell carcinoma
2,0.026831,0.155922,-0.312277,-0.335711,-0.164326,-0.418784,-0.465641,0.293345,-0.622055,-0.398703,...,0.538703,-0.008156,-0.101597,-0.563643,-0.548314,-0.164803,-0.095536,-0.773518,3,basal cell carcinoma
3,0.066918,0.156499,-0.171048,0.088367,-0.435317,0.211593,0.079312,0.120092,-0.916128,-0.131985,...,0.303742,-0.108662,-0.157681,-0.546065,0.475608,0.102519,-0.225175,0.102343,4,basal cell carcinoma
4,-0.014538,0.155935,-0.225166,-0.596145,0.093486,-0.429872,0.303531,0.127815,-0.338632,-0.453110,...,0.231991,0.439281,0.125383,-0.459006,-0.640221,0.262368,-0.139702,-0.480256,5,basal cell carcinoma

In [5]:
df = pd.read_csv('outputs/panderm_d7p.csv')
df.head()

,0,1,2,3,4,5,6,7,8,9,...,1016,1017,1018,1019,1020,1021,1022,1023,image_id,class
0,0.093149,0.155922,-0.227682,0.131200,-0.021234,0.206294,-0.418440,0.222322,-0.729207,-0.040593,...,0.151985,0.256870,-0.177419,-0.852222,-0.112196,-0.166880,-0.261960,0.195685,1,basal cell carcinoma
1,0.074431,0.156090,-0.149146,0.053283,0.158131,-0.160206,0.198405,0.098455,-1.345160,0.027786,...,0.844300,0.128064,-0.222104,-0.524728,-0.106959,0.027761,-0.235939,-0.006325,2,basal cell carcinoma
2,0.026831,0.155922,-0.312277,-0.335711,-0.164326,-0.418784,-0.465640,0.293345,-0.622055,-0.398703,...,0.538703,-0.008156,-0.101598,-0.563643,-0.548314,-0.164803,-0.095536,-0.773517,3,basal cell carcinoma
3,0.066917,0.156499,-0.171048,0.088367,-0.435318,0.211593,0.079311,0.120092,-0.916127,-0.131985,...,0.303742,-0.108662,-0.157681,-0.546065,0.475608,0.102519,-0.225175,0.102343,4,basal cell carcinoma
4,-0.014538,0.155935,-0.225166,-0.596144,0.093486,-0.429872,0.303531,0.127815,-0.338632,-0.453110,...,0.231991,0.439281,0.125383,-0.459006,-0.640221,0.262367,-0.139702,-0.480256,5,basal cell carcinoma